# Generated by Django 3.0.5 on 2021-02-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MongoTestModel',
        ),
    ]
