# Generated by Django 3.0.5 on 2021-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0003_mongotestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mongotestmodel',
            name='binary',
            field=models.BinaryField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mongotestmodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
