# Generated by Django 3.0.5 on 2021-02-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0004_auto_20210204_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongotestmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mongotestmodel',
            name='name',
        ),
    ]
