# Generated by Django 3.0.5 on 2021-02-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0005_auto_20210204_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongotestmodel',
            name='binary',
        ),
        migrations.RemoveField(
            model_name='mongotestmodel',
            name='image',
        ),
    ]
