# Generated by Django 3.0.5 on 2021-02-04 02:01

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0006_auto_20210204_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mongotestmodel',
            name='image',
            field=models.ImageField(default=1, storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='myfiles'), upload_to='authors'),
            preserve_default=False,
        ),
    ]
