# Generated by Django 3.0.5 on 2021-02-04 02:11

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0007_mongotestmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongotestmodel',
            name='image',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='mongo_table'), upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='mongotestmodel',
            table='myfiles',
        ),
    ]
